---
all:
  hosts:
    localhost:
      ansible_connection: local
      initial_heap: 2
      maximum_heap: 6
  children:
    jmeter_servers:
      hosts:
        jmeter11:
        jmeter12:
        jmeter13:
      vars:
        initial_heap: 8
        maximum_heap: 24
